version: '3.8'

services:
  db:
    image: postgres:14
    container_name: bookdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: bookdbgit --version
    ports:
      - "5432:5432"
    volumes:
      - bookdb_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: book-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "cmd/main.go"]

volumes:
  bookdb_data:
